---
# Data Science and Artificial Intelliegence Practicum
## 2.1-modul. Data Analysis: NumPy
---

## 2.1.3 - Boolean Indexing

In [129]:
import numpy as np

In [130]:
# Names
names = np.array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
names

array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U8')

In [131]:
# Data
data = np.random.randn(7, 4)
data

array([[-2.05461503, -0.27117699, -0.187091  , -0.36626331],
       [ 1.15161431,  0.01551423,  1.75320118,  1.37669111],
       [-0.11359492,  1.71793788, -0.92796192,  1.21447225],
       [ 0.14995478, -0.95420184, -0.14884612,  0.34081155],
       [ 0.35536154, -1.57062875,  0.48502826,  0.5321216 ],
       [-0.84026932, -0.27624593,  0.19083656, -1.58840929],
       [ 0.08390862,  0.99524438, -0.04119694,  0.13312157]])

In [132]:
names == "Javohir"

array([False, False, False, False, False,  True, False])

In [133]:
data[names == "Javohir"]  # Javohir's data

array([[-0.84026932, -0.27624593,  0.19083656, -1.58840929]])

In [134]:
data[names == "Elyor"]  # Elyor's data

array([[ 0.14995478, -0.95420184, -0.14884612,  0.34081155],
       [ 0.08390862,  0.99524438, -0.04119694,  0.13312157]])

In [135]:
data[names == "Hasan", 2:]  # Hasan's data's last 2 columns

array([[-0.187091  , -0.36626331],
       [ 0.48502826,  0.5321216 ]])

In [136]:
data[names != "Hasan"]  # returns everyone's data except Hasan's

array([[ 1.15161431,  0.01551423,  1.75320118,  1.37669111],
       [-0.11359492,  1.71793788, -0.92796192,  1.21447225],
       [ 0.14995478, -0.95420184, -0.14884612,  0.34081155],
       [-0.84026932, -0.27624593,  0.19083656, -1.58840929],
       [ 0.08390862,  0.99524438, -0.04119694,  0.13312157]])

In [137]:
data[~(names == "Hasan")] # "~"" equivalent to "!="

array([[ 1.15161431,  0.01551423,  1.75320118,  1.37669111],
       [-0.11359492,  1.71793788, -0.92796192,  1.21447225],
       [ 0.14995478, -0.95420184, -0.14884612,  0.34081155],
       [-0.84026932, -0.27624593,  0.19083656, -1.58840929],
       [ 0.08390862,  0.99524438, -0.04119694,  0.13312157]])

In [140]:
mask = (names=="Hasan") | (names=="Elyor")  # "|" -> or

In [142]:
data[mask]  # Hasan and Elyor's data

array([[-2.05461503, -0.27117699, -0.187091  , -0.36626331],
       [ 0.14995478, -0.95420184, -0.14884612,  0.34081155],
       [ 0.35536154, -1.57062875,  0.48502826,  0.5321216 ],
       [ 0.08390862,  0.99524438, -0.04119694,  0.13312157]])

In [143]:
data

array([[-2.05461503, -0.27117699, -0.187091  , -0.36626331],
       [ 1.15161431,  0.01551423,  1.75320118,  1.37669111],
       [-0.11359492,  1.71793788, -0.92796192,  1.21447225],
       [ 0.14995478, -0.95420184, -0.14884612,  0.34081155],
       [ 0.35536154, -1.57062875,  0.48502826,  0.5321216 ],
       [-0.84026932, -0.27624593,  0.19083656, -1.58840929],
       [ 0.08390862,  0.99524438, -0.04119694,  0.13312157]])

In [144]:
data[data < 0]

array([-2.05461503, -0.27117699, -0.187091  , -0.36626331, -0.11359492,
       -0.92796192, -0.95420184, -0.14884612, -1.57062875, -0.84026932,
       -0.27624593, -1.58840929, -0.04119694])