---
# Data Science and Artificial Intelliegence Practicum
## 2.1-modul. Data Analysis: NumPy
---

## 2.1.8 - Working with files

### **`save`, `load`, `savez`, `savez_compressed`**

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# save an array to a binary file in NumPy .npy format
np.save("data.npy", arr)

In [4]:
# load arrays or pickled objects from .npy, .npz or pickled files
arr1 = np.load("data.npy")
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr2 = np.arange(20)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
# save several arrays into a single file in uncompressed
np.savez("arrays.npz", a=arr, b=arr2)

In [15]:
arrays = np.load("arrays.npz")

In [16]:
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
# save several arrays into a single file in compressed .npz format
np.savez_compressed("arrays_comp.npz", c=arr, d=arr2)

In [20]:
arrays_comp = np.load("arrays_comp.npz")

In [21]:
arrays_comp['c']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arrays_comp['d']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### **`np.savetxt`, `np.loadtxt`**

In [23]:
# save an array to a text file
np.savetxt("arr_text.txt", arr2)

In [24]:
# load data from a text file
arr_text = np.loadtxt("arr_text.txt")
arr_text

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])