---
# Data Science and Artificial Intelliegence Practicum
## 2.1-modul. Data Analysis: NumPy
---

## 2.1.4 - Boolean Indexing

In [ ]:
import numpy as np

In [ ]:
# Names
names = np.array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
names

array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U8')

In [ ]:
# Data
data = np.random.randn(7, 4)
data

array([[-9.44463650e-01,  1.11929220e+00,  4.46843804e-01,
        -3.20724338e-01],
       [ 4.34595121e-01, -5.68236971e-02, -9.28164797e-01,
        -2.51441843e-01],
       [ 1.21789547e+00, -1.01581785e+00,  3.83709538e-02,
        -6.28671253e-02],
       [-1.43385731e+00,  1.01888464e-01, -1.20825698e+00,
         6.27729735e-01],
       [ 2.25196868e+00, -1.16667520e+00,  5.13565211e-04,
        -1.34760677e+00],
       [ 1.26933586e+00,  2.28284428e+00, -1.08515203e-01,
        -3.46523181e-01],
       [ 5.92890980e-01,  1.08777500e+00, -6.70701266e-01,
         2.43480337e-01]])

In [ ]:
names == "Javohir"

array([False, False, False, False, False,  True, False])

In [ ]:
data[names == "Javohir"]  # Javohir's data

array([[-0.84026932, -0.27624593,  0.19083656, -1.58840929]])

In [ ]:
data[names == "Elyor"]  # Elyor's data

array([[ 0.14995478, -0.95420184, -0.14884612,  0.34081155],
       [ 0.08390862,  0.99524438, -0.04119694,  0.13312157]])

In [ ]:
data[names == "Hasan", 2:]  # Hasan's data's last 2 columns

array([[-0.187091  , -0.36626331],
       [ 0.48502826,  0.5321216 ]])

In [ ]:
data[names != "Hasan"]  # returns everyone's data except Hasan's

array([[ 1.15161431,  0.01551423,  1.75320118,  1.37669111],
       [-0.11359492,  1.71793788, -0.92796192,  1.21447225],
       [ 0.14995478, -0.95420184, -0.14884612,  0.34081155],
       [-0.84026932, -0.27624593,  0.19083656, -1.58840929],
       [ 0.08390862,  0.99524438, -0.04119694,  0.13312157]])

In [ ]:
data[~(names == "Hasan")] # "~"" equivalent to "!="

array([[ 1.15161431,  0.01551423,  1.75320118,  1.37669111],
       [-0.11359492,  1.71793788, -0.92796192,  1.21447225],
       [ 0.14995478, -0.95420184, -0.14884612,  0.34081155],
       [-0.84026932, -0.27624593,  0.19083656, -1.58840929],
       [ 0.08390862,  0.99524438, -0.04119694,  0.13312157]])

In [ ]:
mask = (names=="Hasan") | (names=="Elyor")  # "|" -> or

In [ ]:
data[mask]  # Hasan and Elyor's data

array([[-2.05461503, -0.27117699, -0.187091  , -0.36626331],
       [ 0.14995478, -0.95420184, -0.14884612,  0.34081155],
       [ 0.35536154, -1.57062875,  0.48502826,  0.5321216 ],
       [ 0.08390862,  0.99524438, -0.04119694,  0.13312157]])

In [ ]:
data

array([[-2.05461503, -0.27117699, -0.187091  , -0.36626331],
       [ 1.15161431,  0.01551423,  1.75320118,  1.37669111],
       [-0.11359492,  1.71793788, -0.92796192,  1.21447225],
       [ 0.14995478, -0.95420184, -0.14884612,  0.34081155],
       [ 0.35536154, -1.57062875,  0.48502826,  0.5321216 ],
       [-0.84026932, -0.27624593,  0.19083656, -1.58840929],
       [ 0.08390862,  0.99524438, -0.04119694,  0.13312157]])

In [ ]:
data[data < 0]

array([-2.05461503, -0.27117699, -0.187091  , -0.36626331, -0.11359492,
       -0.92796192, -0.95420184, -0.14884612, -1.57062875, -0.84026932,
       -0.27624593, -1.58840929, -0.04119694])